//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iakademi5_proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Products
    {
        public int productID { get; set; }
        public string productcode { get; set; }
        public string productname { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> categoryID { get; set; }
        public Nullable<int> supplierID { get; set; }
        public Nullable<long> stock { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<System.DateTime> adddate { get; set; }
        public string keywords { get; set; }
        public Nullable<int> desidegeri { get; set; }
        public Nullable<int> kdv { get; set; }
        public Nullable<int> tiklamasayisi { get; set; }
        public Nullable<int> coksatanlar { get; set; }
        public Nullable<int> benzer_urunler { get; set; }
        public string notlar { get; set; }
        public Nullable<bool> aktif { get; set; }
    }
}
