//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iakademi5_proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Images
    {
        public int resimID { get; set; }
        public Nullable<int> productID { get; set; }
        public string resimyolu { get; set; }
        public Nullable<bool> aktif { get; set; }
    }
}
